#ifndef PREAMBLE_GLSL
#define PREAMBLE_GLSL

#define POSITION_ATTRIB_LOCATION 0
#define TEXCOORD_ATTRIB_LOCATION 1
#define NORMAL_ATTRIB_LOCATION 2
#define TANGENT_ATTRIB_LOCATION 3
#define BINORMAL_ATTRIB_LOCATION 4

#define MVP_UNIFORM_BLOCK_BINDING 0
#define VEC_UNIFORM_BLOCK_BINDING 1
#define LIGHT_UNIFORM_BLOCK_BINDING 2

#define DIFFUSE_TEXTURE_BINDING 3
#define SPEUCLAR_TEXTURE_BINDING 4
#define NORMAL_TEXTURE_BINDING 5
#define SPECULAR_SHININESS_LOCATION 6

#endif 